// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/mux-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.MuxSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.MuxSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.MuxSDK, name string) (sdk.MuxEntity, error) {
	switch strings.ToLower(name) {
	case "annotation":
		return client.Annotation(nil), nil
	case "ask_question":
		return client.AskQuestion(nil), nil
	case "asset":
		return client.Asset(nil), nil
	case "asset_or_live_stream_id":
		return client.AssetOrLiveStreamId(nil), nil
	case "asset_playback_id":
		return client.AssetPlaybackId(nil), nil
	case "asset_shot":
		return client.AssetShot(nil), nil
	case "create_playback_id":
		return client.CreatePlaybackId(nil), nil
	case "create_track":
		return client.CreateTrack(nil), nil
	case "directive":
		return client.Directive(nil), nil
	case "directive_run_detail":
		return client.DirectiveRunDetail(nil), nil
	case "drm_configuration":
		return client.DrmConfiguration(nil), nil
	case "edit_caption":
		return client.EditCaption(nil), nil
	case "engagement_heatmap":
		return client.EngagementHeatmap(nil), nil
	case "engagement_hotspot":
		return client.EngagementHotspot(nil), nil
	case "find_best_thumbnail":
		return client.FindBestThumbnail(nil), nil
	case "find_key_moment":
		return client.FindKeyMoment(nil), nil
	case "find_scene":
		return client.FindScene(nil), nil
	case "generate_asset_shot":
		return client.GenerateAssetShot(nil), nil
	case "generate_chapter":
		return client.GenerateChapter(nil), nil
	case "generate_engagement_insight":
		return client.GenerateEngagementInsight(nil), nil
	case "generate_premium_caption":
		return client.GeneratePremiumCaption(nil), nil
	case "generate_track_subtitle":
		return client.GenerateTrackSubtitle(nil), nil
	case "incident":
		return client.Incident(nil), nil
	case "input_info":
		return client.InputInfo(nil), nil
	case "job_summary":
		return client.JobSummary(nil), nil
	case "list_all_metric_value":
		return client.ListAllMetricValue(nil), nil
	case "list_breakdown_value":
		return client.ListBreakdownValue(nil), nil
	case "list_delivery_usage":
		return client.ListDeliveryUsage(nil), nil
	case "list_dimension_value":
		return client.ListDimensionValue(nil), nil
	case "list_error":
		return client.ListError(nil), nil
	case "list_export":
		return client.ListExport(nil), nil
	case "list_filter_value":
		return client.ListFilterValue(nil), nil
	case "list_insight":
		return client.ListInsight(nil), nil
	case "list_monitoring_dimension":
		return client.ListMonitoringDimension(nil), nil
	case "list_monitoring_metric":
		return client.ListMonitoringMetric(nil), nil
	case "list_real_time_dimension":
		return client.ListRealTimeDimension(nil), nil
	case "list_real_time_metric":
		return client.ListRealTimeMetric(nil), nil
	case "list_related_incident":
		return client.ListRelatedIncident(nil), nil
	case "list_subview_breakdown_value":
		return client.ListSubviewBreakdownValue(nil), nil
	case "list_subview_comparison_value":
		return client.ListSubviewComparisonValue(nil), nil
	case "list_subview_dimension":
		return client.ListSubviewDimension(nil), nil
	case "list_subview_dimension_value":
		return client.ListSubviewDimensionValue(nil), nil
	case "list_video_view_export":
		return client.ListVideoViewExport(nil), nil
	case "live_stream":
		return client.LiveStream(nil), nil
	case "live_stream_playback_id":
		return client.LiveStreamPlaybackId(nil), nil
	case "metric_timeseries_data":
		return client.MetricTimeseriesData(nil), nil
	case "moderate":
		return client.Moderate(nil), nil
	case "monitoring_breakdown":
		return client.MonitoringBreakdown(nil), nil
	case "monitoring_breakdown_timeseries":
		return client.MonitoringBreakdownTimeseries(nil), nil
	case "monitoring_histogram_timeseries":
		return client.MonitoringHistogramTimeseries(nil), nil
	case "monitoring_timeseries":
		return client.MonitoringTimeseries(nil), nil
	case "overall":
		return client.Overall(nil), nil
	case "playback_restriction":
		return client.PlaybackRestriction(nil), nil
	case "real_time_breakdown":
		return client.RealTimeBreakdown(nil), nil
	case "real_time_histogram_timeseries":
		return client.RealTimeHistogramTimeseries(nil), nil
	case "real_time_timeseries":
		return client.RealTimeTimeseries(nil), nil
	case "signal_live_stream_complete":
		return client.SignalLiveStreamComplete(nil), nil
	case "signing_key":
		return client.SigningKey(nil), nil
	case "simulcast_target":
		return client.SimulcastTarget(nil), nil
	case "static_rendition":
		return client.StaticRendition(nil), nil
	case "subview_breakdown_timeseries":
		return client.SubviewBreakdownTimeseries(nil), nil
	case "subview_overall_value":
		return client.SubviewOverallValue(nil), nil
	case "summarize":
		return client.Summarize(nil), nil
	case "transcription_vocabulary":
		return client.TranscriptionVocabulary(nil), nil
	case "translate_audio":
		return client.TranslateAudio(nil), nil
	case "translate_caption":
		return client.TranslateCaption(nil), nil
	case "update_asset_track":
		return client.UpdateAssetTrack(nil), nil
	case "upload":
		return client.Upload(nil), nil
	case "url_signing_key":
		return client.UrlSigningKey(nil), nil
	case "usage_export":
		return client.UsageExport(nil), nil
	case "video_view":
		return client.VideoView(nil), nil
	case "webhook":
		return client.Webhook(nil), nil
	case "who_am_i":
		return client.WhoAmI(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
