<?php
declare(strict_types=1);

// Mux SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MuxUtility::setRegistrar(function (MuxUtility $u): void {
    $u->clean = [MuxClean::class, 'call'];
    $u->done = [MuxDone::class, 'call'];
    $u->make_error = [MuxMakeError::class, 'call'];
    $u->feature_add = [MuxFeatureAdd::class, 'call'];
    $u->feature_hook = [MuxFeatureHook::class, 'call'];
    $u->feature_init = [MuxFeatureInit::class, 'call'];
    $u->fetcher = [MuxFetcher::class, 'call'];
    $u->make_fetch_def = [MuxMakeFetchDef::class, 'call'];
    $u->make_context = [MuxMakeContext::class, 'call'];
    $u->make_options = [MuxMakeOptions::class, 'call'];
    $u->make_request = [MuxMakeRequest::class, 'call'];
    $u->make_response = [MuxMakeResponse::class, 'call'];
    $u->make_result = [MuxMakeResult::class, 'call'];
    $u->make_point = [MuxMakePoint::class, 'call'];
    $u->make_spec = [MuxMakeSpec::class, 'call'];
    $u->make_url = [MuxMakeUrl::class, 'call'];
    $u->param = [MuxParam::class, 'call'];
    $u->prepare_auth = [MuxPrepareAuth::class, 'call'];
    $u->prepare_body = [MuxPrepareBody::class, 'call'];
    $u->prepare_headers = [MuxPrepareHeaders::class, 'call'];
    $u->prepare_method = [MuxPrepareMethod::class, 'call'];
    $u->prepare_params = [MuxPrepareParams::class, 'call'];
    $u->prepare_path = [MuxPreparePath::class, 'call'];
    $u->prepare_query = [MuxPrepareQuery::class, 'call'];
    $u->graphql_body = [MuxGraphql::class, 'body'];
    $u->graphql_errors = [MuxGraphql::class, 'errors'];
    $u->result_basic = [MuxResultBasic::class, 'call'];
    $u->result_body = [MuxResultBody::class, 'call'];
    $u->result_headers = [MuxResultHeaders::class, 'call'];
    $u->transform_request = [MuxTransformRequest::class, 'call'];
    $u->transform_response = [MuxTransformResponse::class, 'call'];
});
